/**
 * PDF Exporter — Bakes annotations into the PDF and downloads it.
 */
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { bus, Events } from '../core/events.js';
import { state } from '../core/state.js';
import t from '../i18n/index.js';

/**
 * Generate the final PDF bytes with all annotations baked in.
 * Does not modify the active document state.
 * @returns {Promise<Uint8Array>}
 */
export async function generateExportBytes() {
  if (!state.pdfBytes) return null;

  try {
    // Load a fresh copy from current bytes so we don't pollute the live state
    const doc = await PDFDocument.load(state.pdfBytes);
    const pages = doc.getPages();

    // Embed font once for all text annotations
    let font = null;
    if (state.textAnnotations.some(a => a.text?.trim())) {
      font = await doc.embedFont(StandardFonts.Helvetica);
    }

    // Apply text annotations
    for (const ann of state.textAnnotations) {
      const text = ann.text?.trim();
      if (!text) continue;

      const page = pages[ann.page - 1];
      if (!page) continue;

      const { height } = page.getSize();
      const pdfX = ann.pdfX;
      const pdfY = height - ann.pdfY - 12;

      page.drawText(text, {
        x: pdfX,
        y: pdfY,
        size: 12,
        font,
        color: rgb(0, 0, 0),
      });
    }

    // Apply redact rectangles (black cover boxes)
    for (const r of state.redactRects) {
      const page = pages[r.page - 1];
      if (!page) continue;

      const { height } = page.getSize();
      page.drawRectangle({
        x: r.pdfX,
        y: height - r.pdfY - r.pdfH,
        width: r.pdfW,
        height: r.pdfH,
        color: rgb(0, 0, 0),
        opacity: 1,
      });
    }

    // Serialize
    const bytes = await doc.save();
    return bytes;

  } catch (err) {
    console.error('[Exporter] Export error:', err);
    bus.emit(Events.TOAST, {
      msg: t('toastExportError', { error: err.message }),
      type: 'error',
      duration: 5000,
    });
    return null;
  }
}

/**
 * Download the generated bytes as a file.
 */
export function downloadPDF(bytes, originalName) {
  const blob = new Blob([bytes], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  const baseName = originalName.replace(/\.pdf$/i, '');
  anchor.download = `${baseName}_edited.pdf`;
  anchor.click();
  URL.revokeObjectURL(url);
  
  bus.emit(Events.TOAST, {
    msg: t('toastExported', { name: anchor.download }),
    type: 'success',
    duration: 4000,
  });
}
